# Generated by Django 3.2.25 on 2025-10-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_notification_project_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('meeting_reminder', 'Meeting Reminder'), ('chat_mention', 'Chat Mention'), ('activity_alert', 'Activity Alert'), ('project_invitation', 'Project Invitation'), ('system', 'System Notification')], max_length=30),
        ),
    ]
